// Mock student database that can be shared across API routes
export const students = [
  {
    id: "ST-001",
    name: "John Doe",
    email: "john@example.com",
    password: "password", // In a real app, this would be hashed
    rollNo: "CS12345",
    roomNo: "A-101",
    hostel: "A Block",
    contact: "+91 9876543210",
    parentContact: "+91 9876543211",
    firstLogin: false,
    isNewStudent: false,
  },
  {
    id: "ST-002",
    name: "Alice Johnson",
    email: "alice@example.com",
    password: "password",
    rollNo: "CS12346",
    roomNo: "A-102",
    hostel: "A Block",
    contact: "+91 9876543212",
    parentContact: "+91 9876543213",
    firstLogin: true,
    isNewStudent: false,
  },
  {
    id: "ST-003",
    name: "Bob Smith",
    email: "bob@example.com",
    password: "password",
    rollNo: "CS12347",
    roomNo: "A-103",
    hostel: "A Block",
    contact: "+91 9876543214",
    parentContact: "+91 9876543215",
    firstLogin: false,
    isNewStudent: false,
  },
  {
    id: "ST-004",
    name: "Charlie Davis",
    email: "charlie@example.com",
    password: "password",
    rollNo: "CS12348",
    roomNo: "B-101",
    hostel: "B Block",
    contact: "+91 9876543216",
    parentContact: "+91 9876543217",
    firstLogin: true,
    isNewStudent: false,
  },
  // Completely new student with no pre-filled information
  {
    id: "ST-006",
    name: "New User",
    email: "newuser@example.com",
    password: "password",
    rollNo: "",
    roomNo: "",
    hostel: "",
    contact: "",
    parentContact: "",
    firstLogin: true,
    isNewStudent: true, // Flag to identify completely new students
  },
]
